# Paths:  
path_to_data: '/l/users/otabek.nazarov/chexpert/CheXpert-v1.0-small/'
path_to_save_dir: '/l/users/otabek.nazarov/chexpert/saved/'

# Train settings:
image_size: 224
train_batch_size: 32
val_batch_size: 32
num_workers: 16 
lr: 1e-3 
n_epochs: 10
small_eval_size: 1000
eval_freq: 800

# Other configs
send_to_wandb: False
