# Paths:
path_to_data: '/l/users/otabek.nazarov/chexpert/CheXpert-v1.0-small/'
path_to_save_dir: '/l/users/otabek.nazarov/chexpert/CheXpert-v1.0-small/weights/'
runs_title: 'densenet121_pretrained'

# Train settings:
model_name: 'densenet121'
train_batch_size: 32
val_batch_size: 32
num_workers: 16
lr: 1e-4 
n_epochs: 20
small_eval_size: 234
eval_freq: 800

# Other configs
send_to_wandb: True
