# Paths:
path_to_data: '/home/otabek.nazarov/Downloads/research/chexpert/CheXpert-v1.0-small/'
path_to_save_dir: 'weights/'
runs_title: 'resnetblur50'

# Train settings:
model_name: 'resnetblur50'
train_batch_size: 32
val_batch_size: 32
num_workers: 16
lr: 1e-4
n_epochs: 6
small_eval_size: 234
eval_freq: 800
image_size: 224
num_classes: 14

# Other configs
send_to_wandb: True
