# Paths:
path_to_data: '/l/users/otabek.nazarov/chexpert/CheXpert-v1.0-small/'
path_to_save_dir: ''

# Train settings:
model_name: 'densenet121'
train_batch_size: 16
val_batch_size: 1
num_workers: 0
lr: 1e-3 
n_epochs: 2
small_eval_size: 5
eval_freq: 2

# Other configs
send_to_wandb: False
